[build]
# Set the root directory for the build process
rootDirectory = "task_1"

# Explicitly tell Nixpacks to use the Python builder

builder = "nixpacks" 

# Define a custom build command to ensure pip install and migration run.
buildCommand = "pip install -r requirements.txt && python manage.py migrate"

[deploy]
# Define the start command (the server)
startCommand = "gunicorn string_analyzer.wsgi --log-file -"

